services:
  # minio service
  # MinIO is an open-source object storage server compatible with Amazon S3
  minio:
    image: minio/minio:latest
    container_name: dreamshop-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}  # MinIO root user
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}  # MinIO root password
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - dreamshop-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  
# MySQL service
  # MySQL is a popular open-source relational database management system
  mysql:
    image: mysql:8.4
    container_name: dreamshop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./mysql-data:/var/lib/mysql
      
      
    networks:
      - dreamshop-network
    # command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


  # DreamShop application service
  app:
    build: .
    container_name: dreamshop-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # Database
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_PROFILES_ACTIVE: docker    
      
      # JWT
      AUTH_TOKEN_JWT_SECRET: ${AUTH_TOKEN_JWT_SECRET}
      AUTH_TOKEN_EXPIRATION_IN_MILS: ${AUTH_TOKEN_EXPIRATION_IN_MILS}
    ports:
      - "8080:8080"
    networks:
      - dreamshop-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  minio_data:
    driver: local
  # mysql_data:
  #   driver: local
networks:
  dreamshop-network:
    driver: bridge